{
    "rgb": array(
        [
            [
                [21, 21, 22, ..., 23, 23, 22],
                [21, 22, 23, ..., 24, 24, 23],
                [22, 23, 23, ..., 25, 25, 24],
                ...,
                [22, 22, 22, ..., 23, 23, 22],
                [21, 21, 22, ..., 23, 22, 22],
                [20, 21, 21, ..., 22, 21, 21],
            ],
            [
                [25, 26, 27, ..., 30, 29, 28],
                [26, 27, 28, ..., 30, 30, 29],
                [27, 28, 29, ..., 31, 31, 30],
                ...,
                [18, 18, 18, ..., 30, 29, 28],
                [17, 18, 18, ..., 29, 28, 28],
                [16, 17, 17, ..., 28, 28, 27],
            ],
            [
                [34, 35, 36, ..., 41, 40, 39],
                [35, 36, 37, ..., 42, 42, 40],
                [36, 38, 38, ..., 43, 43, 42],
                ...,
                [12, 12, 12, ..., 14, 14, 13],
                [11, 12, 12, ..., 14, 13, 13],
                [11, 11, 11, ..., 13, 13, 13],
            ],
        ],
        dtype=uint8,
    ),
    "inventory": {
        "cur_durability": array(
            [
                1.561e03,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
            ],
            dtype=float32,
        ),
        "max_durability": array(
            [
                1.561e03,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
                -1.000e00,
            ],
            dtype=float32,
        ),
        "name": array(
            [
                "diamond sword",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
                "air",
            ],
            dtype="<U13",
        ),
        "quantity": array(
            [
                1.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            dtype=float32,
        ),
        "variant": array(
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ]
        ),
    },
    "equipment": {
        "cur_durability": array([1561.0, 65.0, 75.0, 80.0, 55.0, 336.0], dtype=float32),
        "max_durability": array([1561.0, 65.0, 75.0, 80.0, 55.0, 336.0], dtype=float32),
        "name": array(
            [
                "diamond sword",
                "leather boots",
                "leather leggings",
                "leather chestplate",
                "leather helmet",
                "shield",
            ],
            dtype="<U18",
        ),
        "quantity": array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype=float32),
        "variant": array([0, 0, 0, 0, 0, 0]),
    },
    "life_stats": {
        "armor": array([7.0], dtype=float32),
        "food": array([20.0], dtype=float32),
        "is_sleeping": array(False),
        "life": array([20.0], dtype=float32),
        "oxygen": array([300.0], dtype=float32),
        "saturation": array([5.0], dtype=float32),
        "xp": array([0.0], dtype=float32),
    },
    "location_stats": {
        "biome_id": array(1),
        "can_see_sky": array(True),
        "is_raining": array(False),
        "light_level": array([15.0], dtype=float32),
        "pitch": array([0.0], dtype=float32),
        "pos": array([33.5, 72.0, 250.5], dtype=float32),
        "rainfall": array([0.4], dtype=float32),
        "sea_level": array([63.0], dtype=float32),
        "sky_light_level": array([0.72372043], dtype=float32),
        "sun_brightness": array([0.9546505], dtype=float32),
        "temperature": array([0.8], dtype=float32),
        "yaw": array([0.0], dtype=float32),
    },
    "nearby_tools": {"table": array(False), "furnace": array(False)},
    "damage_source": {
        "damage_amount": array([0.0], dtype=float32),
        "damage_distance": array([0.0], dtype=float32),
        "damage_pitch": array([0.0], dtype=float32),
        "damage_yaw": array([0.0], dtype=float32),
        "hunger_damage": array([0.0], dtype=float32),
        "is_explosion": array(False),
        "is_fire_damage": array(False),
        "is_magic_damage": array(False),
        "is_projectile": array(False),
        "is_unblockable": array(False),
    },
    "voxels": {
        "block_name": array(
            [
                [
                    ["grass block", "grass block", "grass block"],
                    ["air", "air", "air"],
                    ["air", "air", "air"],
                ],
                [
                    ["grass block", "grass block", "grass block"],
                    ["air", "air", "air"],
                    ["air", "air", "air"],
                ],
                [
                    ["grass block", "grass block", "grass block"],
                    ["grass", "air", "air"],
                    ["air", "air", "air"],
                ],
            ],
            dtype="<U11",
        ),
        "block_meta": array(
            [
                [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                [[0, 0, 0], [1, 0, 0], [0, 0, 0]],
            ]
        ),
        "is_collidable": array(
            [
                [[True, True, True], [True, True, True], [True, True, True]],
                [[True, True, True], [True, True, True], [True, True, True]],
                [[True, True, True], [True, True, True], [True, True, True]],
            ]
        ),
        "is_tool_not_required": array(
            [
                [[True, True, True], [True, True, True], [True, True, True]],
                [[True, True, True], [True, True, True], [True, True, True]],
                [[True, True, True], [True, True, True], [True, True, True]],
            ]
        ),
        "blocks_movement": array(
            [
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
            ]
        ),
        "is_liquid": array(
            [
                [[False, False, False], [False, False, False], [False, False, False]],
                [[False, False, False], [False, False, False], [False, False, False]],
                [[False, False, False], [False, False, False], [False, False, False]],
            ]
        ),
        "is_solid": array(
            [
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
            ]
        ),
        "can_burn": array(
            [
                [[False, False, False], [False, False, False], [False, False, False]],
                [[False, False, False], [False, False, False], [False, False, False]],
                [[False, False, False], [True, False, False], [False, False, False]],
            ]
        ),
        "blocks_light": array(
            [
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
                [[True, True, True], [False, False, False], [False, False, False]],
            ]
        ),
        "cos_look_vec_angle": array(
            [
                [
                    [-0.44495696, -0.16339171, 0.16339171],
                    [-0.5619751, -0.22087598, 0.22087598],
                    [-0.6787121, -0.29440302, 0.29440302],
                ],
                [
                    [-0.49017513, -0.18424739, 0.18424739],
                    [-0.66262794, -0.28286988, 0.28286988],
                    [-0.8832091, -0.53167427, 0.53167427],
                ],
                [
                    [-0.49017513, -0.18424739, 0.18424739],
                    [-0.66262794, -0.28286988, 0.28286988],
                    [-0.8832091, -0.53167427, 0.53167427],
                ],
            ],
            dtype=float32,
        ),
    },
    "masks": {
        "action_type": array([True, True, True, True, False, False, False, True]),
        "action_arg": array(
            [[False], [False], [False], [False], [True], [True], [True], [True]]
        ),
        "equip": array(
            [
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
            ]
        ),
        "place": array(
            [
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
            ]
        ),
        "destroy": array(
            [
                True,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
            ]
        ),
        "craft_smelt": array(
            [
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
            ]
        ),
    },
    "delta_inv": {
        "inc_name_by_craft": array(["air"], dtype="<U3"),
        "inc_quantity_by_craft": array([0.0], dtype=float32),
        "inc_name_by_other": array(["air"], dtype="<U3"),
        "inc_quantity_by_other": array([0.0], dtype=float32),
        "dec_name_by_craft": array(["air", "air", "air", "air"], dtype="<U3"),
        "dec_quantity_by_craft": array([0.0, 0.0, 0.0, 0.0], dtype=float32),
        "dec_name_by_other": array(["air", "air", "air", "air"], dtype="<U3"),
        "dec_quantity_by_other": array([0.0, 0.0, 0.0, 0.0], dtype=float32),
    },
}
